### ISSUE TITLE
Checkpoint 1

### ISSUE THREAD

**Issue by davidtcalabrese** [mad-ent-java-s22/indie-project#1]
@pawaitemadisoncollege 
I wanted to create an issue to get some feedback. I haven't built out the project plan... I just don't know what I'm going to do, this task seems insurmountable with my current knowledge set. I will try to build the project plan out at least one week from the current date.

**Comment by pawaitemadisoncollege** [comment]
@davidtcalabrese I've been thinking about your project ever since you pitched the idea last week. I really think this is going to be such a great way to showcase what you can do!

- [ ] While I appreciate the conciseness of your problem statement, I feel like it's missing a good description of the problem. I don't expect you to do gobs of research or anything, but I think a further explanation of the problem is worthwhile. 
- [ ] User stories would be improved by making them reflect what the user wants to do. For example: "I do not want to be distracted from meaningful issues" might be rewritten to "As a news-reader(?) I only want to see content related to issues that are meaningful to me so that I am not distracted by content that is not meaningful to me."
- [ ] HTTP Cat - what a great find!  
- [ ] One note on the ERD - We'll learn more about this in week 7, but you won't have to store the user's password within your database. AWS Cognito will handle that for us.
- [ ] Will users be able to add articles? Curious where the content will come from.
- [ ] Add user stories for user registration, and all the things the user will be able to do. Consider the ent java project should include sign in, sign up, CRUD on the data.
- [ ] Screen design should reflect the user stories, for example a sign in page, a sign up page, etc.
- [ ] When taking the next cut at your project plan, consider adding in tasks related to implementing the various user stories. May also be a good idea to consider the Checkpoints and what tasks are required to meet those milestones. 

- [ ] I saw your note in your journal about the CriteriaBuilder. Is this still an issue-  I think we chatted about staying at the latest stable build. Not sure if this was related to the beta version or not.

**Comment by davidtcalabrese** [comment]
Thank you for the thorough review. I'm working on all of this stuff this week.
